### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by hsmatis** [telamonian/jupyter-osx-app#2]
It got this far and crashed

(base) Howards-Laptop-2:jupyter-app-master matis$ ./install
downloading chromium...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  108M  100  108M    0     0  7985k      0  0:00:13  0:00:13 --:--:-- 7971k
...done

installing base browser app...
done

cleaning up base browser install files...
done

changing app icon to jupyter...
done

renaming app executable...
done

copying outer wrapper script over to app...
setting vars in outer wrapper script...
sed: can't read s#$[{]*TERM_NAME[}]*#Terminal#g: No such file or directory

**Comment by telamonian** [comment]
Interesting. Haven't seen an error in that part of the program before. Before anything else, two things:

- This is a Mac only program, and doesn't work on Linux
- The `sed` command is annoyingly finnicky, so if you've installed an alternate version of `sed` that may have broken things.

If you're on a Mac and have never touched your `sed` before, then something weird is going on. In that case I'll need some more info to figure out what's going wrong for you. Can you please post here:

- The contents of your `install.conf` file, if you've made any changes to it.
- Some info about `Howards-Laptop-2` (mostly I just need the OS and version).
- Run the command `./install -d` in the app repo dir and post the output here. This will perform a dry run of the install and print out some (hopefully) helpful pathing info.

Some extra info that might be helpful:

- Run the command `$(which sed)`, then the command `strings $(which sed)` in a terminal, and post the complete output here (this will let me know your version of `sed`).
- Run the command `env` and post the complete output (this will let me know if any pre-existing env vars are interfering with the program).

**Comment by telamonian** [comment]
Also, I just pushed a fix for the `sed` command that should make it more universally supported. You can pull the latest version and see if that fixes your problem.

**Comment by hsmatis** [comment]
This got a little farther but did not fully execute:
copying outer wrapper script over to app...
setting vars in outer wrapper script...
sed: can't read s#$[{]*TERM_NAME[}]*#Terminal#g: No such file or directory
(base) Howards-Laptop-2:jupyter-app-master matis$ 

(base) Howards-Laptop-2:jupyter-app-master matis$ which sed
/sw/bin/sed

I have a MacBook Pro  - Version 10.14.5 with 8 GB of memory
[env.txt](https://github.com/telamonian/jupyter-app/files/3378517/env.txt)

**Comment by telamonian** [comment]
> (base) Howards-Laptop-2:jupyter-app-master matis$ which sed
> /sw/bin/sed

That's part of the mystery there. You're using Fink, which at some point installed it's own version of `sed`. I'm a Homebrew user myself, but given the trouble you're having it was most likely GNU `sed`, which is almost but not quite entirely unlike the BSD `sed` that ships with OSX. This is the likely reason why the `sed` command is failing for you but not for me.

So the fix will be to make the `sed` command I'm using universal for GNU/BSD.

> This got a little farther but did not fully execute:

When you say that, do you mean that you pulled the latest update to this repo and tried that? Theoretically at least, the latest change should have fixed the `sed` command for your situation. If it didn't then I need to take another crack at it.

**Comment by telamonian** [comment]
Just now, I installed GNU `sed` on my machine and tried it out with the latest version of this repo. It worked just fine. 

~~So if the latest version is really still failing for you then your version of `sed` is not the problem, and we'll have to look elsewhere for the issue/resolution.~~

## Edit

If I roll back to the old version of the repo and try to use GNU `sed` to install, then I get the exact same error that you do:

```
copying outer wrapper script over to app...
setting vars in outer wrapper script...
gsed: can't read s#$[{]*TERM_NAME[}]*#Terminal#g: No such file or directory
```

So I'm ~90% sure that your version of `sed` is the issue, and that the latest version of the repo should fix the problem (it does for me).

**Comment by telamonian** [comment]
Since there's been no response for a few months, I'm going to assume that the problem has been resolved and close this issue.
