### ISSUE TITLE
Access to "Chromium Safe Storage" is requested on first startup of jupyter-app

### ISSUE THREAD

**Issue by jayqi** [telamonian/jupyter-osx-app#4]
I'm getting two prompts of `Jupyter_bin` asking for keychain access. I don't see why I need it, so I've been hitting deny.

![Screen Shot 2019-10-17 at 9 06 44 AM](https://user-images.githubusercontent.com/2721979/67016319-a1781f00-f0bd-11e9-9104-30cf0a5c806f.png)

The first prompt is blocking the Chromium app from starting up. Once I deny it, it starts up with no problem.

When I deny the second prompt, it seems like it's triggering the auto-terminal-shutdown. If I ignore it, JupyterLab works fine. If I deny it, my terminal session closes, and my JupterLab window that is still open loses connection to all of the kernels. 

macOS High Sierra 10.13.6

Installed from commit `0021964faae8423282ecd4828e16b618c12b90b8`

**Comment by telamonian** [comment]
For any given instance of Chrome or Chromium on OSX, you need to give it access to "Chromium Safe Storage" in your keychain. This value is generated the first time Chrom/-ium is run on your system, and is used to encrypt sensitive user settings, such as logins and password.

Bottom line, Chrom/-ium needs this value to run, so you need to allow access. There is no security risk here

refs:
- https://chromium.googlesource.com/chromium/src/+/master/docs/security/faq.md#does-the-password-manager-store-my-passwords-encrypted-on-disk
- https://bugs.chromium.org/p/chromium/issues/detail?id=466638
- https://forum.vivaldi.net/topic/2385/what-is-the-chrome-safe-storage/17?lang=en-US

the chromium source code where "Chromium Safe Storage" is implemented:
- https://chromium.googlesource.com/chromium/src/+/master/components/os_crypt/keychain_password_mac.mm
